<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-JHSNJM80U4Q" ignored="0" name="Test" tests="8" failures="1" timestamp="2022-02-15T00:20:31 GMT+07:00" time="0.143" errors="0">
  <testcase name="TestNG_SetAvg" time="0.014" classname="online_tusur.unit_online_tusur.Test_NG"/>
  <testcase name="TestAge" time="0.01" classname="online_tusur.unit_online_tusur.Test_NG">
    <failure type="java.lang.AssertionError" message="expected [18] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at online_tusur.unit_online_tusur.Test_NG.TestAge(Test_NG.java:60)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- TestAge -->
  <testcase name="TestAge" time="0.056" classname="online_tusur.unit_online_tusur.Test_NG"/>
  <testcase name="TestAge" time="0.057" classname="online_tusur.unit_online_tusur.Test_NG"/>
  <testcase name="TestAge" time="0.056" classname="online_tusur.unit_online_tusur.Test_NG"/>
  <testcase name="TestLastName" time="0.089" classname="online_tusur.unit_online_tusur.Test_NG_Dynamic"/>
  <testcase name="TestLastName" time="0.089" classname="online_tusur.unit_online_tusur.Test_NG_Dynamic"/>
  <testcase name="TestLastName" time="0.089" classname="online_tusur.unit_online_tusur.Test_NG_Dynamic"/>
</testsuite> <!-- Test -->
