<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="11" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="116" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
    <groups>
    </groups>
    <test name="Test" duration-ms="116" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
      <class name="online_tusur.unit_online_tusur.TestMain">
        <test-method status="FAIL" signature="testMain()[pri:0, instance:online_tusur.unit_online_tusur.TestMain@7d904ff1]" name="testMain" duration-ms="6" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ботвинкина Tamara, 18
Nikulin Ivan, 18
Petrov Konstantin, 33
AVG= 24
MAX= 33
MIN= 18
] but found [Ivan Sidorov
MAX=33
]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ботвинкина Tamara, 18
Nikulin Ivan, 18
Petrov Konstantin, 33
AVG= 24
MAX= 33
MIN= 18
] but found [Ivan Sidorov
MAX=33
]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at online_tusur.unit_online_tusur.TestMain.testMain(TestMain.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMain -->
      </class> <!-- online_tusur.unit_online_tusur.TestMain -->
      <class name="online_tusur.unit_online_tusur.Test_NG_Dynamic">
        <test-method status="PASS" signature="TestLastName()[pri:0, instance:online_tusur.unit_online_tusur.Test_NG_Dynamic@2e73d5eb, instance params:[Pavlova, pavlova]]" name="TestLastName" duration-ms="50" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLastName -->
        <test-method status="PASS" signature="TestLastName()[pri:0, instance:online_tusur.unit_online_tusur.Test_NG_Dynamic@650ae78c, instance params:[Morozov, Morozov]]" name="TestLastName" duration-ms="28" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLastName -->
        <test-method status="PASS" signature="TestLastName()[pri:0, instance:online_tusur.unit_online_tusur.Test_NG_Dynamic@79c5460e, instance params:[Titov, TITOV]]" name="TestLastName" duration-ms="7" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLastName -->
      </class> <!-- online_tusur.unit_online_tusur.Test_NG_Dynamic -->
      <class name="online_tusur.unit_online_tusur.Test_NG">
        <test-method status="PASS" signature="setUp()[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="setUp" is-config="true" duration-ms="4" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="TestNG_SetFirstName(java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestNG_SetFirstName" duration-ms="40" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected null, but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected null, but was:<>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotNull(Assert.java:756)
at org.junit.Assert.assertNull(Assert.java:738)
at org.junit.Assert.assertNull(Assert.java:748)
at online_tusur.unit_online_tusur.Test_NG.TestNG_SetFirstName(Test_NG.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNG_SetFirstName -->
        <test-method status="FAIL" signature="TestNG_SetLastName(java.lang.String)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestNG_SetLastName" duration-ms="41" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected null, but was:<>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected null, but was:<>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotNull(Assert.java:756)
at org.junit.Assert.assertNull(Assert.java:738)
at org.junit.Assert.assertNull(Assert.java:748)
at online_tusur.unit_online_tusur.Test_NG.TestNG_SetLastName(Test_NG.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNG_SetLastName -->
        <test-method status="PASS" signature="TestNG_SetAvg(int,int)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestNG_SetAvg" duration-ms="15" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestNG_SetAvg -->
        <test-method status="FAIL" signature="TestAge(int,int)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestAge" duration-ms="13" started-at="2022-02-21T12:29:04 GMT+07:00" data-provider="data" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [18] but found [50]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at online_tusur.unit_online_tusur.Test_NG.TestAge(Test_NG.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAge -->
        <test-method status="PASS" signature="TestAge(int,int)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestAge" duration-ms="36" started-at="2022-02-21T12:29:04 GMT+07:00" data-provider="data" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAge -->
        <test-method status="PASS" signature="TestAge(int,int)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestAge" duration-ms="36" started-at="2022-02-21T12:29:04 GMT+07:00" data-provider="data" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAge -->
        <test-method status="PASS" signature="TestAge(int,int)[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="TestAge" duration-ms="35" started-at="2022-02-21T12:29:04 GMT+07:00" data-provider="data" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <params>
            <param index="0">
              <value>
                <![CDATA[0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestAge -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:online_tusur.unit_online_tusur.Test_NG@4190bc8a]" name="tearDown" is-config="true" duration-ms="0" started-at="2022-02-21T12:29:04 GMT+07:00" finished-at="2022-02-21T12:29:04 GMT+07:00">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- online_tusur.unit_online_tusur.Test_NG -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
